name: Deploy GPU Server

on:
  push:
    branches: [dev, main]
    paths:
      - 'ai/inference/**'
      - 'ai/api.py'
      - 'ai/requirements.txt'
      - 'ai/Dockerfile'
      - 'docker-compose.gpu.yml'
  pull_request:
    branches: [dev, main]
    paths:
      - 'ai/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Syntax Check

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ai/requirements.txt

      - name: Install Dependencies
        run: pip install -r ai/requirements.txt

      - name: Syntax Check
        run: python -m py_compile ai/api.py

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    name: Deploy to GPU Server
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GPU Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GPU_PRIVATE_IP }}
          username: ${{ secrets.GPU_USER }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.APP_HOST }}
          proxy_username: ${{ secrets.APP_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          proxy_port: 52222
          command_timeout: 30m
          script: |
            set -e

            if [ ! -d ~/MovieSir/.git ]; then
              echo "ðŸ“Œ Git ì €ìž¥ì†Œ ì—†ìŒ, í´ë¡  ì¤‘..."
              if [ -d ~/MovieSir/ai/training ]; then
                mv ~/MovieSir/ai/training ~/backup-training
              fi
              rm -rf ~/MovieSir
              git clone https://github.com/${{ github.repository }}.git ~/MovieSir
              if [ -d ~/backup-training ]; then
                cp -r ~/backup-training/* ~/MovieSir/ai/training/
              fi
            fi

            echo "ðŸ“Œ ìµœì‹  ì½”ë“œ ê°€ì ¸ì˜¤ê¸°"
            cd ~/MovieSir
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}

            echo "ðŸ“Œ í™˜ê²½ë³€ìˆ˜ íŒŒì¼ ìƒì„±"
            cat > .env.production << 'ENVEOF'
            ${{ secrets.ENV_PRODUCTION_GPU }}
            ENVEOF

            echo "ðŸ“Œ ê¸°ì¡´ ì»¨í…Œì´ë„ˆ ì¤‘ì§€"
            docker compose -f docker-compose.gpu.yml --env-file .env.production down || true

            echo "ðŸ“Œ ë¹Œë“œ ìºì‹œ ì •ë¦¬"
            docker builder prune -f || true

            echo "ðŸ“Œ AI ì´ë¯¸ì§€ ë¹Œë“œ"
            cd ~/MovieSir/ai && docker build -t moviesir-ai:latest .

            echo "ðŸ“Œ AI ì»¨í…Œì´ë„ˆ ì‹œìž‘"
            cd ~/MovieSir && docker compose -f docker-compose.gpu.yml --env-file .env.production up -d --no-build

            echo "ðŸ“Œ ë¯¸ì‚¬ìš© ì´ë¯¸ì§€ ì •ë¦¬"
            docker image prune -f || true

            echo "ðŸ“Œ AI ì„œë¹„ìŠ¤ í—¬ìŠ¤ì²´í¬"
            sleep 5
            curl -s http://localhost:8001/health || echo "âš ï¸ í—¬ìŠ¤ì²´í¬ ì‹¤íŒ¨ (ì„œë¹„ìŠ¤ ì‹œìž‘ ì¤‘ì¼ ìˆ˜ ìžˆìŒ)"

            echo "âœ… GPU ì„œë²„ ë°°í¬ ì™„ë£Œ"
