name: Backend CI/CD

on:
  push:
    branches: [dev, main]
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - 'nginx/**'
  pull_request:
    branches: [dev, main]
    paths:
      - 'backend/**'
      - 'nginx/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Syntax Check

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Syntax Check
        run: python -m py_compile backend/main.py

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    name: Deploy to Server
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 52222
          command_timeout: 30m
          script: |
            set -e

            echo "ðŸ“Œ ìµœì‹  ì½”ë“œ ê°€ì ¸ì˜¤ê¸°"
            cd ~/MovieSir
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}

            echo "ðŸ“Œ í™˜ê²½ë³€ìˆ˜ íŒŒì¼ ìƒì„±"
            cat > .env.production << 'ENVEOF'
            ${{ secrets.ENV_PRODUCTION_APP }}
            ENVEOF

            echo "ðŸ“Œ ë¹Œë” ìºì‹œ ì •ë¦¬"
            docker builder prune -f || true

            echo "ðŸ“Œ ê¸°ì¡´ ì»¨í…Œì´ë„ˆ ì¤‘ì§€"
            docker compose --env-file .env.production down || true

            echo "ðŸ“Œ ë°±ì—”ë“œ ì»¨í…Œì´ë„ˆ ë¹Œë“œ ë° ì‹œìž‘"
            docker compose --env-file .env.production up -d --build backend redis dozzle

            echo "ðŸ“Œ ë¯¸ì‚¬ìš© ì´ë¯¸ì§€ ì •ë¦¬"
            docker image prune -f || true

            echo "ðŸ“Œ ë°±ì—”ë“œ í—¬ìŠ¤ì²´í¬"
            sleep 3
            curl -s http://localhost:8000/ || echo "âš ï¸ í—¬ìŠ¤ì²´í¬ ëŒ€ê¸°ì¤‘"

            echo "ðŸ“Œ nginx ì„¤ì • ì—…ë°ì´íŠ¸"
            sudo cp ~/MovieSir/nginx/moviesir.conf /etc/nginx/sites-enabled/moviesir
            sudo nginx -t && sudo systemctl reload nginx

            echo "âœ… ë°±ì—”ë“œ ë°°í¬ ì™„ë£Œ"
